import type { NextPage } from "next";
import Head from "next/head";
import { useRecoilValue } from "recoil";
import { authAtom } from "../libs/recoil/auth";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const router = useRouter();
  const value = useRecoilValue(authAtom);
  console.log("value", value);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="max-w-xl mx-auto">
        <div className="p-4">
          <h1>main page</h1>
          <p>
            <span className="font-bold text-lg">access_token:</span>{" "}
            {value.accessToken}
          </p>
          <p>
            <span className="font-bold text-lg">username:</span>{" "}
            {value.user.username}
          </p>
        </div>

        {!value.accessToken && (
          <div className="flex justify-center">
            <button
              className="rounded-md bg-teal-600 py-2 px-4 text-white"
              onClick={() => router.push("/login")}
            >
              로그인
            </button>
          </div>
        )}
      </div>
    </div>
  );
};

export default Home;
