import type { NextPage } from "next";
import Head from "next/head";
import { useRecoilValue } from "recoil";
import { authAtom } from "../libs/recoil/auth";

const Home: NextPage = () => {
  const value = useRecoilValue(authAtom);
  console.log("value", value);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="max-w-xl mx-auto">
        <div className="p-4 flex justify-center items-center">main</div>
        <p>{value.accessToken}</p>
        <p>{value.user.username}</p>
      </div>
    </div>
  );
};

export default Home;
